# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iotdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem', models.IntegerField(max_length=50)),
                ('hum', models.IntegerField(max_length=50)),
                ('door', models.IntegerField(max_length=10)),
                ('feng', models.IntegerField(max_length=10)),
                ('indoor', models.IntegerField(max_length=10)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
