# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20170523_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdata',
            name='door',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='feng',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='hum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='indoor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='iotdata',
            name='tem',
            field=models.IntegerField(),
        ),
    ]
